/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('fr' | 'es' | 'en' | 'de')
    | ('fr' | 'es' | 'en' | 'de')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'fr' | 'es' | 'en' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Identifiant d'URL, ex. « accueil », « philosophie ».
   */
  slug: string;
  /**
   * Composition de la page par blocs (en-tête, texte, citation, index, signature, appel à l’action).
   */
  layout?:
    | (
        | {
            variant?: ('cream' | 'petrol' | 'media') | null;
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            /**
             * Image de fond (hero plein écran, variante « media » — ex. accueil).
             */
            image?: (number | null) | Media;
            /**
             * URL d’image de fond directe si pas d’upload (ex. /literature_cafe.jpg).
             */
            imageUrl?: string | null;
            portrait?: (number | null) | Media;
            /**
             * URL d’image directe si pas d’upload.
             */
            portraitUrl?: string | null;
            portraitCaption?: string | null;
            /**
             * Étiquette « à venir » sur l’emplacement photo. Optionnel.
             */
            comingSoon?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            /**
             * Phrase forte (grande serif).
             */
            lead?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statement';
          }
        | {
            items?:
              | {
                  term: string;
                  caption?: string | null;
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'manifesto';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            rows?:
              | {
                  term: string;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'values';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            items?:
              | {
                  title: string;
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            items?:
              | {
                  title: string;
                  text?: string | null;
                  tags?:
                    | {
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  imageCaption?: string | null;
                  imageUrl?: string | null;
                  comingSoon?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceDetail';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            items?:
              | {
                  title: string;
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            items?:
              | {
                  tag?: string | null;
                  title: string;
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'milestones';
          }
        | {
            eyebrow?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            signatureName?: string | null;
            role?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'story';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            items?:
              | {
                  caption: string;
                  tag?: string | null;
                  image?: (number | null) | Media;
                  imageUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            eyebrow?: string | null;
            quote: string;
            signatureName?: string | null;
            role?: string | null;
            portrait?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'founder';
          }
        | {
            sectionTitle?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'prose';
          }
        | {
            variant?: ('cream' | 'petrol') | null;
            quote: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pullquote';
          }
        | {
            variant?: ('petrol' | 'inline') | null;
            heading: string;
            text?: string | null;
            buttonLabel?: string | null;
            buttonHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            nameLabel?: string | null;
            emailLabel?: string | null;
            projectLabel?: string | null;
            projectOptions?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            messageLabel?: string | null;
            messagePlaceholder?: string | null;
            submitLabel?: string | null;
            writeLabel?: string | null;
            meetLabel?: string | null;
            meetLocation?: string | null;
            meetNote?: string | null;
            langsLabel?: string | null;
            langsValue?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
      )[]
    | null;
  /**
   * Chapô / résumé court (repli si la page n’a pas de blocs).
   */
  excerpt?: string | null;
  /**
   * Contenu de repli (utilisé seulement si « layout » est vide).
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Afficher cette page dans le menu de navigation.
   */
  showInNav?: boolean | null;
  /**
   * Ordre dans le menu (croissant).
   */
  navOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              intro?: T;
              ctaLabel?: T;
              ctaHref?: T;
              image?: T;
              imageUrl?: T;
              portrait?: T;
              portraitUrl?: T;
              portraitCaption?: T;
              comingSoon?: T;
              id?: T;
              blockName?: T;
            };
        statement?:
          | T
          | {
              eyebrow?: T;
              lead?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        manifesto?:
          | T
          | {
              items?:
                | T
                | {
                    term?: T;
                    caption?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        values?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              rows?:
                | T
                | {
                    term?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        serviceDetail?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    tags?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    imageCaption?: T;
                    imageUrl?: T;
                    comingSoon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        milestones?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        story?:
          | T
          | {
              eyebrow?: T;
              body?: T;
              signatureName?: T;
              role?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    caption?: T;
                    tag?: T;
                    image?: T;
                    imageUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        founder?:
          | T
          | {
              eyebrow?: T;
              quote?: T;
              signatureName?: T;
              role?: T;
              portrait?: T;
              id?: T;
              blockName?: T;
            };
        prose?:
          | T
          | {
              sectionTitle?: T;
              body?: T;
              note?: T;
              id?: T;
              blockName?: T;
            };
        pullquote?:
          | T
          | {
              variant?: T;
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              variant?: T;
              heading?: T;
              text?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              nameLabel?: T;
              emailLabel?: T;
              projectLabel?: T;
              projectOptions?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              messageLabel?: T;
              messagePlaceholder?: T;
              submitLabel?: T;
              writeLabel?: T;
              meetLabel?: T;
              meetLocation?: T;
              meetNote?: T;
              langsLabel?: T;
              langsValue?: T;
              id?: T;
              blockName?: T;
            };
      };
  excerpt?: T;
  content?: T;
  showInNav?: T;
  navOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Baseline (footer) — ex. « Maison de bibliothèques privées… ».
   */
  tagline?: string | null;
  contactEmail?: string | null;
  /**
   * Domaine affiché (ex. noema-library.ch).
   */
  domain?: string | null;
  /**
   * Lieu (ex. Genève, Suisse).
   */
  location?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  contactEmail?: T;
  domain?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}